# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main_scrollablepdZOJV.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLayout,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QScrollArea, QSizePolicy, QSlider,
    QSpinBox, QStatusBar, QTabWidget, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1090, 780)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setMaximumSize(QSize(1090, 780))
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.actionLoadDirectory = QAction(MainWindow)
        self.actionLoadDirectory.setObjectName(u"actionLoadDirectory")
        self.actionSaveDirectory = QAction(MainWindow)
        self.actionSaveDirectory.setObjectName(u"actionSaveDirectory")
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        self.actionPoints = QAction(MainWindow)
        self.actionPoints.setObjectName(u"actionPoints")
        self.actionBounding_Boxes = QAction(MainWindow)
        self.actionBounding_Boxes.setObjectName(u"actionBounding_Boxes")
        self.actionPoints_2 = QAction(MainWindow)
        self.actionPoints_2.setObjectName(u"actionPoints_2")
        self.actionPoints_2.setCheckable(True)
        self.actionBounding_Boxes_2 = QAction(MainWindow)
        self.actionBounding_Boxes_2.setObjectName(u"actionBounding_Boxes_2")
        self.actionBounding_Boxes_2.setCheckable(True)
        self.actionBounding_Boxes_2.setChecked(True)
        self.actionFPS = QAction(MainWindow)
        self.actionFPS.setObjectName(u"actionFPS")
        self.actionFPS.setCheckable(True)
        self.actionOriginal_Frame = QAction(MainWindow)
        self.actionOriginal_Frame.setObjectName(u"actionOriginal_Frame")
        self.actionOriginal_Frame.setCheckable(True)
        self.actionCollate_Data_NPM = QAction(MainWindow)
        self.actionCollate_Data_NPM.setObjectName(u"actionCollate_Data_NPM")
        self.actionDetails = QAction(MainWindow)
        self.actionDetails.setObjectName(u"actionDetails")
        self.actionDetails.setCheckable(True)
        self.actionDirection = QAction(MainWindow)
        self.actionDirection.setObjectName(u"actionDirection")
        self.actionDirection.setCheckable(True)
        self.actionDirection.setChecked(True)
        self.actionSpeed = QAction(MainWindow)
        self.actionSpeed.setObjectName(u"actionSpeed")
        self.actionSpeed.setCheckable(True)
        self.actionSpeed.setChecked(True)
        self.actionAngular_Velocity = QAction(MainWindow)
        self.actionAngular_Velocity.setObjectName(u"actionAngular_Velocity")
        self.actionAngular_Velocity.setCheckable(True)
        self.actionAngular_Velocity.setChecked(True)
        self.actionMedian_Velocity = QAction(MainWindow)
        self.actionMedian_Velocity.setObjectName(u"actionMedian_Velocity")
        self.actionMedian_Velocity_2 = QAction(MainWindow)
        self.actionMedian_Velocity_2.setObjectName(u"actionMedian_Velocity_2")
        self.actionMedian_Velocity_2.setCheckable(True)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionShow = QAction(MainWindow)
        self.actionShow.setObjectName(u"actionShow")
        self.actionShow.setCheckable(True)
        self.actionShow.setChecked(True)
        self.actionLock_Size = QAction(MainWindow)
        self.actionLock_Size.setObjectName(u"actionLock_Size")
        self.actionLock_Size.setCheckable(True)
        self.actionAlignment_Angle = QAction(MainWindow)
        self.actionAlignment_Angle.setObjectName(u"actionAlignment_Angle")
        self.actionAlignment_Angle.setCheckable(True)
        self.actionAlignment_Angle.setChecked(True)
        self.action20x = QAction(MainWindow)
        self.action20x.setObjectName(u"action20x")
        self.action60x = QAction(MainWindow)
        self.action60x.setObjectName(u"action60x")
        self.actionOpen_Video = QAction(MainWindow)
        self.actionOpen_Video.setObjectName(u"actionOpen_Video")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy1)
        self.scrollArea.setMinimumSize(QSize(0, 0))
        self.scrollArea.setMaximumSize(QSize(1091, 901))
        self.scrollArea.setFrameShape(QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1072, 708))
        self.layoutWidget = QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 1, 1051, 701))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.layoutWidget)
        self.frame.setObjectName(u"frame")
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMinimumSize(QSize(660, 570))
        self.frame.setMaximumSize(QSize(660, 570))
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(8)
        self.frame.setMidLineWidth(0)
        self.frame_8 = QFrame(self.frame)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 10, 641, 31))
        sizePolicy1.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy1)
        self.frame_8.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_2 = QLabel(self.frame_8)
        self.trackingTitle_2.setObjectName(u"trackingTitle_2")
        self.trackingTitle_2.setGeometry(QRect(0, 0, 641, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.trackingTitle_2.setFont(font)
        self.trackingTitle_2.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_2.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_2.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayoutWidget_2 = QWidget(self.frame)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(250, 540, 182, 31))
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setSizeConstraint(QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.playButton = QPushButton(self.horizontalLayoutWidget_2)
        self.playButton.setObjectName(u"playButton")
        icon = QIcon(QIcon.fromTheme(u"media-playback-start"))
        self.playButton.setIcon(icon)
        self.playButton.setCheckable(False)
        self.playButton.setChecked(False)
        self.playButton.setFlat(True)

        self.horizontalLayout_10.addWidget(self.playButton)

        self.pauseButton = QPushButton(self.horizontalLayoutWidget_2)
        self.pauseButton.setObjectName(u"pauseButton")
        icon1 = QIcon(QIcon.fromTheme(u"media-playback-pause"))
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setCheckable(False)
        self.pauseButton.setFlat(True)

        self.horizontalLayout_10.addWidget(self.pauseButton)

        self.recordButton = QPushButton(self.horizontalLayoutWidget_2)
        self.recordButton.setObjectName(u"recordButton")
        self.recordButton.setMaximumSize(QSize(100, 16777215))
        self.recordButton.setCheckable(True)
        self.recordButton.setFlat(False)

        self.horizontalLayout_10.addWidget(self.recordButton)

        self.restartButton = QPushButton(self.horizontalLayoutWidget_2)
        self.restartButton.setObjectName(u"restartButton")
        icon2 = QIcon(QIcon.fromTheme(u"view-refresh"))
        self.restartButton.setIcon(icon2)
        self.restartButton.setFlat(True)

        self.horizontalLayout_10.addWidget(self.restartButton)


        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.frame_2 = QFrame(self.layoutWidget)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy1.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy1)
        self.frame_2.setMinimumSize(QSize(370, 570))
        self.frame_2.setMaximumSize(QSize(370, 570))
        self.frame_2.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(8)
        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 10, 351, 31))
        sizePolicy1.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy1)
        self.frame_6.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_3 = QLabel(self.frame_6)
        self.trackingTitle_3.setObjectName(u"trackingTitle_3")
        self.trackingTitle_3.setGeometry(QRect(0, 0, 347, 31))
        sizePolicy1.setHeightForWidth(self.trackingTitle_3.sizePolicy().hasHeightForWidth())
        self.trackingTitle_3.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setUnderline(False)
        self.trackingTitle_3.setFont(font1)
        self.trackingTitle_3.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_3.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_3.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget1 = QWidget(self.frame_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(11, 51, 351, 511))
        self.verticalLayout_12 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.threshold_5 = QLabel(self.layoutWidget1)
        self.threshold_5.setObjectName(u"threshold_5")
        self.threshold_5.setMaximumSize(QSize(16777215, 28))
        font2 = QFont()
        font2.setPointSize(12)
        self.threshold_5.setFont(font2)
        self.threshold_5.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_5.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_5.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.threshold_5)

        self.autoLabel = QLabel(self.layoutWidget1)
        self.autoLabel.setObjectName(u"autoLabel")
        self.autoLabel.setEnabled(False)
        self.autoLabel.setMinimumSize(QSize(0, 0))
        self.autoLabel.setMaximumSize(QSize(50, 16777215))
        self.autoLabel.setFont(font2)
        self.autoLabel.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.autoLabel.setFrameShape(QFrame.Shape.NoFrame)
        self.autoLabel.setFrameShadow(QFrame.Shadow.Raised)
        self.autoLabel.setTextFormat(Qt.TextFormat.RichText)
        self.autoLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.autoLabel)

        self.autoToggle = QCheckBox(self.layoutWidget1)
        self.autoToggle.setObjectName(u"autoToggle")
        self.autoToggle.setEnabled(False)
        self.autoToggle.setMaximumSize(QSize(20, 16777215))

        self.horizontalLayout_2.addWidget(self.autoToggle)

        self.invertLabel = QLabel(self.layoutWidget1)
        self.invertLabel.setObjectName(u"invertLabel")
        self.invertLabel.setEnabled(False)
        self.invertLabel.setMinimumSize(QSize(0, 0))
        self.invertLabel.setMaximumSize(QSize(50, 16777215))
        self.invertLabel.setFont(font2)
        self.invertLabel.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.invertLabel.setFrameShape(QFrame.Shape.NoFrame)
        self.invertLabel.setFrameShadow(QFrame.Shadow.Raised)
        self.invertLabel.setTextFormat(Qt.TextFormat.RichText)
        self.invertLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.invertLabel)

        self.invertToggle = QCheckBox(self.layoutWidget1)
        self.invertToggle.setObjectName(u"invertToggle")
        self.invertToggle.setEnabled(False)
        self.invertToggle.setMaximumSize(QSize(20, 16777215))

        self.horizontalLayout_2.addWidget(self.invertToggle)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.thresholdToggle = QCheckBox(self.layoutWidget1)
        self.thresholdToggle.setObjectName(u"thresholdToggle")
        self.thresholdToggle.setFont(font2)
        self.thresholdToggle.setCheckable(True)

        self.horizontalLayout_13.addWidget(self.thresholdToggle)

        self.thresholdSlider = QSlider(self.layoutWidget1)
        self.thresholdSlider.setObjectName(u"thresholdSlider")
        self.thresholdSlider.setEnabled(False)
        self.thresholdSlider.setMaximum(100)
        self.thresholdSlider.setOrientation(Qt.Orientation.Horizontal)
        self.thresholdSlider.setInvertedAppearance(False)
        self.thresholdSlider.setInvertedControls(False)
        self.thresholdSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.thresholdSlider.setTickInterval(10)

        self.horizontalLayout_13.addWidget(self.thresholdSlider)

        self.thresholdValue = QSpinBox(self.layoutWidget1)
        self.thresholdValue.setObjectName(u"thresholdValue")
        self.thresholdValue.setEnabled(False)
        self.thresholdValue.setMinimumSize(QSize(100, 0))
        self.thresholdValue.setFont(font2)
        self.thresholdValue.setMaximum(100)

        self.horizontalLayout_13.addWidget(self.thresholdValue)


        self.verticalLayout_2.addLayout(self.horizontalLayout_13)


        self.verticalLayout_12.addLayout(self.verticalLayout_2)

        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.horizontalLayout_19 = QHBoxLayout()
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.contrast_2 = QLabel(self.layoutWidget1)
        self.contrast_2.setObjectName(u"contrast_2")
        self.contrast_2.setMaximumSize(QSize(16777215, 28))
        self.contrast_2.setFont(font2)
        self.contrast_2.setFrameShape(QFrame.Shape.NoFrame)
        self.contrast_2.setFrameShadow(QFrame.Shadow.Raised)
        self.contrast_2.setTextFormat(Qt.TextFormat.RichText)
        self.contrast_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_19.addWidget(self.contrast_2)

        self.adaptMethod = QComboBox(self.layoutWidget1)
        self.adaptMethod.addItem("")
        self.adaptMethod.addItem("")
        self.adaptMethod.setObjectName(u"adaptMethod")
        self.adaptMethod.setEnabled(False)
        self.adaptMethod.setMaximumSize(QSize(75, 16777215))

        self.horizontalLayout_19.addWidget(self.adaptMethod)


        self.verticalLayout_9.addLayout(self.horizontalLayout_19)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.adaptToggle = QCheckBox(self.layoutWidget1)
        self.adaptToggle.setObjectName(u"adaptToggle")
        self.adaptToggle.setFont(font2)

        self.horizontalLayout_11.addWidget(self.adaptToggle)

        self.adaptSliderArea = QSlider(self.layoutWidget1)
        self.adaptSliderArea.setObjectName(u"adaptSliderArea")
        self.adaptSliderArea.setEnabled(False)
        self.adaptSliderArea.setMinimum(0)
        self.adaptSliderArea.setMaximum(99)
        self.adaptSliderArea.setSingleStep(3)
        self.adaptSliderArea.setValue(21)
        self.adaptSliderArea.setOrientation(Qt.Orientation.Horizontal)
        self.adaptSliderArea.setInvertedAppearance(False)
        self.adaptSliderArea.setInvertedControls(False)
        self.adaptSliderArea.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.adaptSliderArea.setTickInterval(9)

        self.horizontalLayout_11.addWidget(self.adaptSliderArea)

        self.adaptValueArea = QSpinBox(self.layoutWidget1)
        self.adaptValueArea.setObjectName(u"adaptValueArea")
        self.adaptValueArea.setEnabled(False)
        self.adaptValueArea.setMinimumSize(QSize(80, 0))
        self.adaptValueArea.setMaximumSize(QSize(80, 16777215))
        font3 = QFont()
        font3.setPointSize(10)
        self.adaptValueArea.setFont(font3)
        self.adaptValueArea.setMinimum(3)
        self.adaptValueArea.setMaximum(99)
        self.adaptValueArea.setSingleStep(2)
        self.adaptValueArea.setValue(21)

        self.horizontalLayout_11.addWidget(self.adaptValueArea)

        self.adaptSliderC = QSlider(self.layoutWidget1)
        self.adaptSliderC.setObjectName(u"adaptSliderC")
        self.adaptSliderC.setEnabled(False)
        self.adaptSliderC.setMinimum(-25)
        self.adaptSliderC.setMaximum(25)
        self.adaptSliderC.setValue(4)
        self.adaptSliderC.setOrientation(Qt.Orientation.Horizontal)
        self.adaptSliderC.setInvertedAppearance(False)
        self.adaptSliderC.setInvertedControls(False)
        self.adaptSliderC.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.adaptSliderC.setTickInterval(10)

        self.horizontalLayout_11.addWidget(self.adaptSliderC)

        self.adaptValueC = QSpinBox(self.layoutWidget1)
        self.adaptValueC.setObjectName(u"adaptValueC")
        self.adaptValueC.setEnabled(False)
        self.adaptValueC.setMinimumSize(QSize(80, 0))
        self.adaptValueC.setFont(font3)
        self.adaptValueC.setMinimum(-25)
        self.adaptValueC.setMaximum(25)
        self.adaptValueC.setValue(4)

        self.horizontalLayout_11.addWidget(self.adaptValueC)


        self.verticalLayout_9.addLayout(self.horizontalLayout_11)


        self.verticalLayout_12.addLayout(self.verticalLayout_9)

        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.contour_2 = QLabel(self.layoutWidget1)
        self.contour_2.setObjectName(u"contour_2")
        self.contour_2.setMaximumSize(QSize(16777215, 28))
        self.contour_2.setFont(font2)
        self.contour_2.setFrameShape(QFrame.Shape.NoFrame)
        self.contour_2.setFrameShadow(QFrame.Shadow.Raised)
        self.contour_2.setTextFormat(Qt.TextFormat.RichText)
        self.contour_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_10.addWidget(self.contour_2)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.embossToggle = QCheckBox(self.layoutWidget1)
        self.embossToggle.setObjectName(u"embossToggle")
        self.embossToggle.setFont(font2)

        self.horizontalLayout_12.addWidget(self.embossToggle)

        self.embossSlider = QSlider(self.layoutWidget1)
        self.embossSlider.setObjectName(u"embossSlider")
        self.embossSlider.setEnabled(False)
        self.embossSlider.setFont(font2)
        self.embossSlider.setMinimum(-100)
        self.embossSlider.setMaximum(100)
        self.embossSlider.setOrientation(Qt.Orientation.Horizontal)
        self.embossSlider.setInvertedAppearance(False)
        self.embossSlider.setInvertedControls(False)
        self.embossSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.embossSlider.setTickInterval(10)

        self.horizontalLayout_12.addWidget(self.embossSlider)

        self.embossValue = QSpinBox(self.layoutWidget1)
        self.embossValue.setObjectName(u"embossValue")
        self.embossValue.setEnabled(False)
        self.embossValue.setMinimumSize(QSize(100, 0))
        self.embossValue.setFont(font2)
        self.embossValue.setMinimum(-100)
        self.embossValue.setMaximum(100)

        self.horizontalLayout_12.addWidget(self.embossValue)


        self.verticalLayout_10.addLayout(self.horizontalLayout_12)


        self.verticalLayout_12.addLayout(self.verticalLayout_10)

        self.verticalLayout_16 = QVBoxLayout()
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.blurTitle_2 = QLabel(self.layoutWidget1)
        self.blurTitle_2.setObjectName(u"blurTitle_2")
        self.blurTitle_2.setMaximumSize(QSize(16777215, 28))
        self.blurTitle_2.setFont(font2)
        self.blurTitle_2.setFrameShape(QFrame.Shape.NoFrame)
        self.blurTitle_2.setFrameShadow(QFrame.Shadow.Raised)
        self.blurTitle_2.setTextFormat(Qt.TextFormat.RichText)
        self.blurTitle_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_16.addWidget(self.blurTitle_2)

        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.blurToggle = QCheckBox(self.layoutWidget1)
        self.blurToggle.setObjectName(u"blurToggle")
        self.blurToggle.setFont(font2)

        self.horizontalLayout_15.addWidget(self.blurToggle)

        self.blurSlider = QSlider(self.layoutWidget1)
        self.blurSlider.setObjectName(u"blurSlider")
        self.blurSlider.setEnabled(False)
        self.blurSlider.setMaximum(100)
        self.blurSlider.setOrientation(Qt.Orientation.Horizontal)
        self.blurSlider.setInvertedAppearance(False)
        self.blurSlider.setInvertedControls(False)
        self.blurSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.blurSlider.setTickInterval(10)

        self.horizontalLayout_15.addWidget(self.blurSlider)

        self.blurValue = QSpinBox(self.layoutWidget1)
        self.blurValue.setObjectName(u"blurValue")
        self.blurValue.setEnabled(False)
        self.blurValue.setMinimumSize(QSize(100, 0))
        self.blurValue.setFont(font2)
        self.blurValue.setMaximum(100)
        self.blurValue.setDisplayIntegerBase(10)

        self.horizontalLayout_15.addWidget(self.blurValue)


        self.verticalLayout_16.addLayout(self.horizontalLayout_15)


        self.verticalLayout_12.addLayout(self.verticalLayout_16)

        self.verticalLayout_14 = QVBoxLayout()
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.dilationTitle_3 = QLabel(self.layoutWidget1)
        self.dilationTitle_3.setObjectName(u"dilationTitle_3")
        self.dilationTitle_3.setMaximumSize(QSize(16777215, 28))
        self.dilationTitle_3.setFont(font2)
        self.dilationTitle_3.setFrameShape(QFrame.Shape.NoFrame)
        self.dilationTitle_3.setFrameShadow(QFrame.Shadow.Raised)
        self.dilationTitle_3.setTextFormat(Qt.TextFormat.RichText)
        self.dilationTitle_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_14.addWidget(self.dilationTitle_3)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.dilationToggle = QCheckBox(self.layoutWidget1)
        self.dilationToggle.setObjectName(u"dilationToggle")
        self.dilationToggle.setFont(font2)

        self.horizontalLayout_16.addWidget(self.dilationToggle)

        self.dilationSlider = QSlider(self.layoutWidget1)
        self.dilationSlider.setObjectName(u"dilationSlider")
        self.dilationSlider.setEnabled(False)
        self.dilationSlider.setMinimum(0)
        self.dilationSlider.setMaximum(5)
        self.dilationSlider.setPageStep(1)
        self.dilationSlider.setOrientation(Qt.Orientation.Horizontal)
        self.dilationSlider.setInvertedAppearance(False)
        self.dilationSlider.setInvertedControls(False)
        self.dilationSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.dilationSlider.setTickInterval(1)

        self.horizontalLayout_16.addWidget(self.dilationSlider)

        self.dilationValue = QSpinBox(self.layoutWidget1)
        self.dilationValue.setObjectName(u"dilationValue")
        self.dilationValue.setEnabled(False)
        self.dilationValue.setMinimumSize(QSize(100, 0))
        self.dilationValue.setFont(font2)
        self.dilationValue.setMinimum(0)
        self.dilationValue.setMaximum(5)
        self.dilationValue.setDisplayIntegerBase(10)

        self.horizontalLayout_16.addWidget(self.dilationValue)


        self.verticalLayout_14.addLayout(self.horizontalLayout_16)


        self.verticalLayout_12.addLayout(self.verticalLayout_14)

        self.verticalLayout_11 = QVBoxLayout()
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.threshold_2 = QLabel(self.layoutWidget1)
        self.threshold_2.setObjectName(u"threshold_2")
        self.threshold_2.setMaximumSize(QSize(16777215, 28))
        self.threshold_2.setFont(font2)
        self.threshold_2.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_2.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_2.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_7.addWidget(self.threshold_2)

        self.subBackMethod = QComboBox(self.layoutWidget1)
        self.subBackMethod.addItem("")
        self.subBackMethod.addItem("")
        self.subBackMethod.setObjectName(u"subBackMethod")
        self.subBackMethod.setEnabled(False)
        self.subBackMethod.setMaximumSize(QSize(75, 16777215))

        self.horizontalLayout_7.addWidget(self.subBackMethod)


        self.verticalLayout_11.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.subBackToggle = QCheckBox(self.layoutWidget1)
        self.subBackToggle.setObjectName(u"subBackToggle")
        self.subBackToggle.setFont(font2)

        self.horizontalLayout_4.addWidget(self.subBackToggle)

        self.subBackSlider = QSlider(self.layoutWidget1)
        self.subBackSlider.setObjectName(u"subBackSlider")
        self.subBackSlider.setEnabled(False)
        self.subBackSlider.setMaximum(100)
        self.subBackSlider.setOrientation(Qt.Orientation.Horizontal)
        self.subBackSlider.setInvertedAppearance(False)
        self.subBackSlider.setInvertedControls(False)
        self.subBackSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.subBackSlider.setTickInterval(10)

        self.horizontalLayout_4.addWidget(self.subBackSlider)

        self.subBackValue = QSpinBox(self.layoutWidget1)
        self.subBackValue.setObjectName(u"subBackValue")
        self.subBackValue.setEnabled(False)
        self.subBackValue.setMinimumSize(QSize(100, 0))
        self.subBackValue.setFont(font2)
        self.subBackValue.setMaximum(100)

        self.horizontalLayout_4.addWidget(self.subBackValue)


        self.verticalLayout_11.addLayout(self.horizontalLayout_4)


        self.verticalLayout_12.addLayout(self.verticalLayout_11)


        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)

        self.frame_4 = QFrame(self.layoutWidget)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy1.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy1)
        self.frame_4.setMinimumSize(QSize(370, 111))
        self.frame_4.setMaximumSize(QSize(661, 111))
        self.frame_4.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_4.setLineWidth(8)
        self.frame_7 = QFrame(self.frame_4)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 10, 641, 31))
        sizePolicy1.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy1)
        self.frame_7.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_4 = QLabel(self.frame_7)
        self.trackingTitle_4.setObjectName(u"trackingTitle_4")
        self.trackingTitle_4.setGeometry(QRect(0, 0, 641, 31))
        sizePolicy1.setHeightForWidth(self.trackingTitle_4.sizePolicy().hasHeightForWidth())
        self.trackingTitle_4.setSizePolicy(sizePolicy1)
        self.trackingTitle_4.setFont(font1)
        self.trackingTitle_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.trackingTitle_4.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_4.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_4.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.progressBar = QProgressBar(self.frame_4)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 60, 631, 31))
        self.progressBar.setValue(0)
        self.progressBar.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)

        self.frame_3 = QFrame(self.layoutWidget)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy1.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy1)
        self.frame_3.setMinimumSize(QSize(370, 111))
        self.frame_3.setMaximumSize(QSize(370, 111))
        self.frame_3.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(8)
        self.frame_5 = QFrame(self.frame_3)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 10, 347, 31))
        sizePolicy1.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy1)
        self.frame_5.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle = QLabel(self.frame_5)
        self.trackingTitle.setObjectName(u"trackingTitle")
        self.trackingTitle.setGeometry(QRect(0, 0, 347, 31))
        sizePolicy1.setHeightForWidth(self.trackingTitle.sizePolicy().hasHeightForWidth())
        self.trackingTitle.setSizePolicy(sizePolicy1)
        self.trackingTitle.setFont(font1)
        self.trackingTitle.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.trackingTitle.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget2 = QWidget(self.frame_3)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 50, 351, 55))
        self.verticalLayout = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.threshold_3 = QLabel(self.layoutWidget2)
        self.threshold_3.setObjectName(u"threshold_3")
        self.threshold_3.setFont(font2)
        self.threshold_3.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_3.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_3.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.threshold_3)

        self.horizontalLayout_18 = QHBoxLayout()
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.frameDiffToggle = QCheckBox(self.layoutWidget2)
        self.frameDiffToggle.setObjectName(u"frameDiffToggle")
        self.frameDiffToggle.setFont(font2)

        self.horizontalLayout_18.addWidget(self.frameDiffToggle)

        self.frameDiffSlider = QSlider(self.layoutWidget2)
        self.frameDiffSlider.setObjectName(u"frameDiffSlider")
        self.frameDiffSlider.setEnabled(False)
        self.frameDiffSlider.setMinimum(0)
        self.frameDiffSlider.setMaximum(1000)
        self.frameDiffSlider.setValue(25)
        self.frameDiffSlider.setOrientation(Qt.Orientation.Horizontal)
        self.frameDiffSlider.setInvertedAppearance(False)
        self.frameDiffSlider.setInvertedControls(False)
        self.frameDiffSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.frameDiffSlider.setTickInterval(100)

        self.horizontalLayout_18.addWidget(self.frameDiffSlider)

        self.frameDiffValue = QSpinBox(self.layoutWidget2)
        self.frameDiffValue.setObjectName(u"frameDiffValue")
        self.frameDiffValue.setEnabled(False)
        self.frameDiffValue.setMinimumSize(QSize(80, 0))
        self.frameDiffValue.setMaximumSize(QSize(80, 16777215))
        self.frameDiffValue.setFont(font3)
        self.frameDiffValue.setMinimum(0)
        self.frameDiffValue.setMaximum(999)
        self.frameDiffValue.setValue(25)

        self.horizontalLayout_18.addWidget(self.frameDiffValue)

        self.frameDiffSliderMax = QSlider(self.layoutWidget2)
        self.frameDiffSliderMax.setObjectName(u"frameDiffSliderMax")
        self.frameDiffSliderMax.setEnabled(False)
        self.frameDiffSliderMax.setMinimum(0)
        self.frameDiffSliderMax.setMaximum(1000)
        self.frameDiffSliderMax.setValue(25)
        self.frameDiffSliderMax.setOrientation(Qt.Orientation.Horizontal)
        self.frameDiffSliderMax.setInvertedAppearance(False)
        self.frameDiffSliderMax.setInvertedControls(False)
        self.frameDiffSliderMax.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.frameDiffSliderMax.setTickInterval(100)

        self.horizontalLayout_18.addWidget(self.frameDiffSliderMax)

        self.frameDiffValueMax = QSpinBox(self.layoutWidget2)
        self.frameDiffValueMax.setObjectName(u"frameDiffValueMax")
        self.frameDiffValueMax.setEnabled(False)
        self.frameDiffValueMax.setMinimumSize(QSize(80, 0))
        self.frameDiffValueMax.setFont(font3)
        self.frameDiffValueMax.setMinimum(0)
        self.frameDiffValueMax.setMaximum(999)
        self.frameDiffValueMax.setValue(100)

        self.horizontalLayout_18.addWidget(self.frameDiffValueMax)


        self.verticalLayout.addLayout(self.horizontalLayout_18)


        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_4.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1090, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuClear = QMenu(self.menubar)
        self.menuClear.setObjectName(u"menuClear")
        self.menuClear.setTearOffEnabled(False)
        self.menuScale_Bar = QMenu(self.menuClear)
        self.menuScale_Bar.setObjectName(u"menuScale_Bar")
        self.menuMain = QMenu(self.menubar)
        self.menuMain.setObjectName(u"menuMain")
        self.menuVideos = QMenu(self.menubar)
        self.menuVideos.setObjectName(u"menuVideos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuVideos.menuAction())
        self.menuFile.addAction(self.actionLoadDirectory)
        self.menuFile.addAction(self.actionSaveDirectory)
        self.menuFile.addAction(self.actionOpen_Video)
        self.menuClear.addAction(self.actionClear)
        self.menuClear.addAction(self.menuScale_Bar.menuAction())
        self.menuClear.addAction(self.actionFPS)
        self.menuClear.addAction(self.actionDetails)
        self.menuClear.addAction(self.actionMedian_Velocity_2)
        self.menuScale_Bar.addAction(self.actionEdit)
        self.menuScale_Bar.addAction(self.actionShow)
        self.menuScale_Bar.addSeparator()
        self.menuScale_Bar.addAction(self.action20x)
        self.menuScale_Bar.addAction(self.action60x)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionPoints_2)
        self.menuMain.addAction(self.actionBounding_Boxes_2)
        self.menuMain.addAction(self.actionOriginal_Frame)
        self.menuMain.addAction(self.actionDirection)
        self.menuMain.addAction(self.actionSpeed)
        self.menuMain.addAction(self.actionAngular_Velocity)
        self.menuMain.addAction(self.actionAlignment_Angle)
        self.menuMain.addSeparator()

        self.retranslateUi(MainWindow)
        self.subBackToggle.toggled.connect(self.subBackMethod.setEnabled)
        self.subBackToggle.toggled.connect(self.subBackValue.setEnabled)
        self.subBackSlider.valueChanged.connect(self.subBackValue.setValue)
        self.subBackToggle.toggled.connect(self.subBackSlider.setEnabled)
        self.subBackValue.valueChanged.connect(self.subBackSlider.setValue)
        self.frameDiffToggle.toggled.connect(self.frameDiffSliderMax.setEnabled)
        self.frameDiffToggle.toggled.connect(self.frameDiffValue.setEnabled)
        self.frameDiffToggle.toggled.connect(self.frameDiffSlider.setEnabled)
        self.frameDiffValue.valueChanged.connect(self.frameDiffSlider.setValue)
        self.frameDiffSlider.valueChanged.connect(self.frameDiffValue.setValue)
        self.frameDiffToggle.toggled.connect(self.frameDiffValueMax.setEnabled)

        self.playButton.setDefault(False)
        self.recordButton.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionLoadDirectory.setText(QCoreApplication.translate("MainWindow", u"Load Directory", None))
        self.actionSaveDirectory.setText(QCoreApplication.translate("MainWindow", u"Save Directory", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.actionPoints.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.actionBounding_Boxes.setText(QCoreApplication.translate("MainWindow", u"Bounding Boxes", None))
        self.actionPoints_2.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.actionBounding_Boxes_2.setText(QCoreApplication.translate("MainWindow", u"Bounding Boxes", None))
        self.actionFPS.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.actionOriginal_Frame.setText(QCoreApplication.translate("MainWindow", u"Original Frame", None))
        self.actionCollate_Data_NPM.setText(QCoreApplication.translate("MainWindow", u"Collate by Voltage (NPM only)", None))
        self.actionDetails.setText(QCoreApplication.translate("MainWindow", u"Details", None))
        self.actionDirection.setText(QCoreApplication.translate("MainWindow", u"Arrows", None))
        self.actionSpeed.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.actionAngular_Velocity.setText(QCoreApplication.translate("MainWindow", u"Angular Velocity", None))
        self.actionMedian_Velocity.setText(QCoreApplication.translate("MainWindow", u"Median Velocity", None))
        self.actionMedian_Velocity_2.setText(QCoreApplication.translate("MainWindow", u"Median Velocity", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionShow.setText(QCoreApplication.translate("MainWindow", u"Show", None))
        self.actionLock_Size.setText(QCoreApplication.translate("MainWindow", u"Lock Size", None))
        self.actionAlignment_Angle.setText(QCoreApplication.translate("MainWindow", u"Alignment Angle", None))
        self.action20x.setText(QCoreApplication.translate("MainWindow", u"20x", None))
        self.action60x.setText(QCoreApplication.translate("MainWindow", u"60x", None))
        self.actionOpen_Video.setText(QCoreApplication.translate("MainWindow", u"Open Video", None))
#if QT_CONFIG(tooltip)
        self.actionOpen_Video.setToolTip(QCoreApplication.translate("MainWindow", u"This will automatically set load directory", None))
#endif // QT_CONFIG(tooltip)
        self.trackingTitle_2.setText(QCoreApplication.translate("MainWindow", u"Video", None))
        self.playButton.setText("")
        self.pauseButton.setText("")
        self.recordButton.setText(QCoreApplication.translate("MainWindow", u"Batch Record", None))
        self.restartButton.setText("")
        self.trackingTitle_3.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.threshold_5.setText(QCoreApplication.translate("MainWindow", u"Threshold", None))
        self.autoLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.autoToggle.setText("")
        self.invertLabel.setText(QCoreApplication.translate("MainWindow", u"Invert", None))
        self.invertToggle.setText("")
        self.thresholdToggle.setText("")
        self.contrast_2.setText(QCoreApplication.translate("MainWindow", u"Adaptive Threshold", None))
        self.adaptMethod.setItemText(0, QCoreApplication.translate("MainWindow", u"Mean", None))
        self.adaptMethod.setItemText(1, QCoreApplication.translate("MainWindow", u"Gaussian", None))

        self.adaptToggle.setText("")
        self.contour_2.setText(QCoreApplication.translate("MainWindow", u"Emboss", None))
        self.embossToggle.setText("")
        self.blurTitle_2.setText(QCoreApplication.translate("MainWindow", u"Gaussian Blur", None))
        self.blurToggle.setText("")
        self.dilationTitle_3.setText(QCoreApplication.translate("MainWindow", u"Dilation", None))
        self.dilationToggle.setText("")
        self.threshold_2.setText(QCoreApplication.translate("MainWindow", u"Subtract Background", None))
        self.subBackMethod.setItemText(0, QCoreApplication.translate("MainWindow", u"KNN", None))
        self.subBackMethod.setItemText(1, QCoreApplication.translate("MainWindow", u"MOG2", None))

        self.subBackToggle.setText("")
        self.trackingTitle_4.setText(QCoreApplication.translate("MainWindow", u"Progress", None))
        self.trackingTitle.setText(QCoreApplication.translate("MainWindow", u"Detection", None))
        self.threshold_3.setText(QCoreApplication.translate("MainWindow", u"Frame Differencing", None))
        self.frameDiffToggle.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuClear.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuScale_Bar.setTitle(QCoreApplication.translate("MainWindow", u"Scale Bar", None))
        self.menuMain.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuVideos.setTitle(QCoreApplication.translate("MainWindow", u"Videos", None))
    # retranslateUi

